[book]
title = "100 Days Of Kubernetes"
authors = ["Anais Urlichs"]
language = "en"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
site-url = "/"
git-repository-url = "https://github.com/100daysofkubernetes/100DaysOfKubernetes"